import "./globals.css";
import { ArticleProvider } from "../../context/ArticleContext";
import React from "react";

export const metadata = {
  title: "NY Times Most Popular Articles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <ArticleProvider>{children}</ArticleProvider>
      </body>
    </html>
  );
}
